// <auto-generated />
using System;
using MarketData.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketData.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketDataDbContext))]
    partial class MarketDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketData.Infrastructure.Persistence.TickEntity", b =>
                {
                    b.Property<string>("Exchange")
                        .HasColumnType("text")
                        .HasColumnName("exchange");

                    b.Property<string>("Ticker")
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ts");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("price");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("volume");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ingested_at");

                    b.HasKey("Exchange", "Ticker", "Timestamp", "Price", "Volume");

                    b.HasIndex("Ticker", "Timestamp")
                        .HasDatabaseName("ix_ticks_ticker_ts");

                    b.ToTable("ticks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
